### ISSUE TITLE
Unable to connect MySQL server using the layer 

### ISSUE THREAD

**Issue by ashwiniimnair** [kuharan/Lambda-Layers#1]
Able to 'Import pyodbc' ,However, could not connect to MYSQL server.  
 "errorMessage": "('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')",
What could be the possible reason for this in AWS lambda?

**Comment by kuharan** [comment]
Its a sql server odbc driver. I have not tested it for mysql.
Though mysql can be connected directly in aws lambda. Check out the aws docs.

**Comment by kuharan** [comment]
Closing as there was no response from the author for a long time.
