### ISSUE TITLE
No build script included / binaries not trusted

### ISSUE THREAD

**Issue by freimer** [kuharan/Lambda-Layers#2]
Please provide a build script for this so people can recreate the layer as needed, for multiple reasons:
1) Security - how can we trust your code and the binaries?
2) Maintainability - need the ability to update to new versions of drivers and Python modules.

Thanks

**Comment by kowenhouston** [comment]
From [this stackoverflow article](https://stackoverflow.com/questions/47682991/aws-lambda-function-to-connect-to-sql-server-with-python) found [this github gist](https://gist.github.com/carlochess/658a98589709f46dbb3d20502e48556b) that seems to get very close to what has been built here.

**Comment by kuharan** [comment]
Thank you @kowenhouston for answering that. I have followed the same steps except for the fact that the driver is ODBC 17. I hope that answers your question @freimer.
