### ISSUE TITLE
Login timeout expired

### ISSUE THREAD

**Issue by rahuls24** [kuharan/Lambda-Layers#4]
Whenever I try to connect with database it(pyodbc) is throwing error "('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)') ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')" on aws lambda. 

I have done all the things mention in your [medium blog](https://medium.com/analytics-vidhya/aws-lambda-python-ms-sql-server-the-easy-way-e7667d371cc5) but still getting the above error.

**Comment by kuharan** [comment]
Hi @rahuls24, sorry for the late response. Please check the database for firewall settings or VPC issues.

**Comment by kuharan** [comment]
There has been no response from you for 1 month, I am closing this. But do feel free to raise issues to improve the layer.
