### ISSUE TITLE
Can you do a package for Python 3.9?

### ISSUE THREAD

**Issue by KrunchMuffin** [kuharan/Lambda-Layers#6]
That would be great.

**Comment by kuharan** [comment]
Are you looking for one specific layer in 3.9?

**Comment by DimaCi** [comment]
> Are you looking for one specific layer in 3.9?

for the pyodbc... if you could kindly update it to version 3.11 or make a tutorial and post it on youtube on how to do it

**Comment by Sosotess93** [comment]
Please cannot find the one on 3.8 or higher can you update ?

**Comment by kuharan** [comment]
Between juggling the chaos of job changes and the everyday whirlwind we call life (just like you all) 🤣, I've been as busy as a bee and couldn't contribute as much as I did in the past. But fear not! I'm determined to carve out more time for us to hang out. Also, I'll be adding step-by-step instructions so you can craft your own lambda layers and join in the fun!
