### ISSUE TITLE
Can you update the documentation for the process to create layers?

### ISSUE THREAD

**Issue by AdrianoNicolucci** [kuharan/Lambda-Layers#8]
Hi, I think what you are doing is great. If others want other people to contribute, can you please update the readme to add the steps to create additional lambda layers for other packages? 

For example, I would like to add  pyodbc for python 3.10

**Comment by kuharan** [comment]
Ahoy there! I know am super late in replying to you. 

Thanks a ton for the kudos! Your enthusiasm is contagious. As for those lambda layers, fear not, my friend! I'm already on it, concocting a magical document to sprinkle some goodness into our readme. But here's the twist: I seem to have misplaced the password to my virtual machine where I used to conjure up those layers. But fret not, I'm channeling my inner Sherlock to crack that code wide open soon. Stay tuned for the layerlicious update!
